### ISSUE TITLE
Shiva Analyzer Throwing Error.

### ISSUE THREAD

**Issue by Waseem-farooqui** [shiva-spampot/shiva#15] opened 2015-09-16 14:31 UTC
I am running Shiva, After receiving Spam mail, **Analyzer logs** throw me this error.
    
    2015-09-16 16:38:53,351 - routing - ERROR - !!! ERROR handling app.handlers.sample.FORWARD
    Traceback (most recent call last):
      File "/opt/shiva-installer/shiva/shivaAnalyzer/local/lib/python2.7/site-packages/lamson/routing.py", line 375, in call_safely
    func(message, **kwargs)
      File "/opt/shiva-installer/shiva/shivaAnalyzer/local/lib/python2.7/site-packages/lamson/routing.py", line 495, in routing_wrapper
    next_state = func(message, *args, **kw)
      File "/opt/shiva-installer/shiva/shivaAnalyzer/analyzer/app/handlers/sample.py", line 25, in FORWARD
    relay.deliver(message)
      File "/opt/shiva-installer/shiva/shivaAnalyzer/local/lib/python2.7/site-packages/lamson/server.py", line 137, in deliver
    relay_host.sendmail(sender, recipient, str(message))
      File "/usr/lib/python2.7/smtplib.py", line 742, in sendmail
    raise SMTPRecipientsRefused(senderrs)
    SMTPRecipientsRefused: {u'tester@*.*.*.*': (550, 'relay not permitted')}

But Afterwards It stores the spam email in db ??
What might be the reason.

**Comment by b0nd** [comment] 2015-09-17 03:29
May I know what were you expecting at this point?

**Comment by Waseem-farooqui** [comment] 2015-09-17 05:28
I am not expecting  **routing - ERROR - !!! ERROR handling app.handlers.sample.FORWARD** and **SMTPRecipientsRefused: {u'tester@*.*.*.*': (550, 'relay not permitted')}**.
I should not throw any error or exception.

**Comment by RahulBinjve** [comment] 2015-09-18 13:08
Hi @Waseem-farooqui,

Glad to see you using and reporting the issues you are encountering in SHIVA. As the error message says, **"routing - ERROR - !!! ERROR handling app.handlers.sample.FORWARD and SMTPRecipientsRefused: {u'tester@...': (550, 'relay not permitted')}."** , what this means is that SHIVA encountered error while trying to relay the spam. There might be various reasons behind it. 
* Did you configure exim correctly using the supplied exim file?
* Did you set the relay host and relay port correctly in shiva.conf file? 
* Does your ISP allows you to send mails? Many ISPs block sending or relaying mails from domestic IPs.

If relaying the spam is not needed, might I suggest you to set the "relay" option as False in config file? As far as I can see, this error message is related to relaying part which is handled by exim. Please, let us know if you are able to find the cause/fix of this error.

Thank you.

**Comment by RahulBinjve** [comment] 2015-11-29 13:19
Closing the issue as it is related to relay being not permitted.

**Closed by RahulBinjve** 2015-11-29 13:19 UTC
